# Swagger/OpenAPI definition
openapi: 3.1.0
info:
  title: Academic Management System API
  description: API documentation for AMS backend.
  contact:
    name: TechGeex Team
    email: sorbopriyo@gmail.com
  version: v1.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths: {}
components: {}
